source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Cake_Example' do
  pod 'Cake', :path => '../'
end

target 'Cake_Tests' do
  pod 'Cake', :path => '../'

  pod 'FBSnapshotTestCase'
end
